### ISSUE TITLE
cannot colocate function "neword" and table "warehouse"

### ISSUE THREAD

**Issue by mumair5393** [citusdata/citus-benchmark#2]
Hi,

While running the chbenchmark on a single instance cluster with one coordinator and two worker nodes. I ran into the following error. The benchmark is able to complete and produces the results. But I was wondering if this error might somehow corrupt the results? 

Vuser 1:CREATING TPCC INDEXES
Vuser 1:CREATING TPCC STORED PROCEDURES
Error in Virtual User 1: ERROR:  cannot colocate function "neword" and table "warehouse"
DETAIL:  Citus currently only supports colocating function with distributed tables that are created using streaming replication model.
HINT:  When distributing tables make sure that citus.replication_model = 'streaming'

Thanks!

**Comment by marcocitus** [comment]
Hi @mumair5393 , the results will be correct, but the transactional part of the benchmark will be slower.

If you add the following to postgresql.conf,
```
citus.replication_model = 'streaming'
```
you should not see the error and get better results.

We are deprecating this (legacy) GUC in the next Citus release to simplify the user experience.
